apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-payment-cluster-ip
  labels:
    app: payment
spec:
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: payment
  type: ClusterIP
