apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-user-deployment
  labels:
    app: user
spec:
  replicas: {{ .Values.user.replicaCount }}
  selector:
    matchLabels:
      app: user
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: akrtmwk/nestjs-user:latest
          envFrom:
            - configMapRef:
                name: user-config-map
            - secretRef:
                name: user-secret
          ports:
            - containerPort: 3001
          livenessProbe:
            tcpSocket:
              port: 3001
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 3001
            periodSeconds: 5