apiVersion: v1
kind: Secret
metadata:
  name: user-secret
data:
  DB_URL: {{ .Values.user.db_url | b64enc }}
  JWT_REFRESH_SECRET: {{ .Values.user.jwt_refresh_secret | b64enc }}
  JWT_ACCESS_SECRET: {{ .Values.user.jwt_access_secret | b64enc }}