apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-product-cluster-ip
  labels:
    app: product
spec:
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: product
  type: ClusterIP