apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-order-cluster-ip
  labels:
    app: order
spec:
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: order
  type: ClusterIP