apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-order-deployment
  labels:
    app: order
spec:
  replicas: {{ .Values.order.replicaCount }}
  selector:
    matchLabels:
      app: order
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-container
          image: akrtmwk/nestjs-order:latest
          envFrom:
            - configMapRef:
                name: order-config-map
            - secretRef:
                name: order-secret
          ports:
            - containerPort: 3001
          livenessProbe:
            tcpSocket:
              port: 3001
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 3001
            periodSeconds: 5