apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config-map
data:
  HTTP_PORT: "3000"
  USER_GRPC_URL: "{{ .Chart.Name }}-user-cluster-ip:3001"
  ORDER_GRPC_URL: "{{ .Chart.Name }}-order-cluster-ip:3001"