apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-gateway-deployment
  labels:
    app: gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-container
          image: akrtmwk/nestjs-gateway:latest
          envFrom:
            - configMapRef:
                name: gateway-config-map
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              port: 3000
              path: "/"
            periodSeconds: 5